# Generated by Django 2.1 on 2018-08-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.IntegerField(choices=[(1, 'fastweb')])),
                ('title', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=60)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
